### PR TITLE
[finishes #163621878] Modified meetups

### PR DESCRIPTION
**Pull request by a-braham**
### What does this PR do?
Creates UX for viewing meetups.
### Description of Task to be completed?
Create the Ux for viewing meetups. Solved the link error
### How should this be manually tested?
- git clone this repo
`git clone https://github.com/a-braham/Questioner-UC.git`
- Cd into the project directory
`Cd Questioner-UX`
- switch into the develop branch
`git checkout develop`
- Install the requirements by running
`sudo apt-get install npm`
`npm install -s webpack`
`npm install -s webpack-cli`
- Then run
`npm start`
### What are the relevant pivotal tracker stories?
#163441725
### Screenshots
screenshot from 2019-02-06 00-48-57

### CODE REVIEW

**Comment by Ogutu-Brian** [comment]
This is really great :+1: @a-braham

**Comment by ceexon** [comment]
Add a link to the hosted app
We want to test :laughing: :rofl:

**Comment by a-braham** [comment]
@kburudi link to heroku ama link ya pages

**Comment by ceexon** [comment]
The Fetched UI @a-braham

**Comment by a-braham** [comment]
Oooh, chill nilink na heroku, nitatuma link

**Pull request merged**
